### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by M-Gonzalo** [sooperset/mcp-atlassian#4]
> error: unrecognized subcommand 'mcp-atlassian' Usage: uvx [OPTIONS] <COMMAND> For more information, try '--help'. MCP error -1: Connection closed

What could be the reason? Thanks in advance

**Comment by M-Gonzalo** [comment]
I'm using from Cline if it's any help

**Comment by M-Gonzalo** [comment]
I tried `uvx run` and it seems to be the way, but:

![image](https://github.com/user-attachments/assets/acbb46ff-dd66-43cb-b040-ee5d20b94bab)

Even though I have python 3.13 installed too

**Comment by sooperset** [comment]
Hi @M-Gonzalo 

I'm actively using this package without issues. To help diagnose your problem, could you try running the package locally with these steps?

1. Clone the repository:
```bash
git clone https://github.com/sooperset/mcp-atlassian.git
cd ~/Documents/mcp_atlassian
```

2. Set up your `.env` file with your Atlassian credentials
3. Run the package using:
```bash
uv --directory ~/Documents/mcp_atlassian run mcp-atlassian
```

**Comment by M-Gonzalo** [comment]
> Hi @M-Gonzalo
> 
> I'm actively using this package without issues. To help diagnose your problem, could you try running the package locally with these steps?
> 
>     1. Clone the repository:
> 
> 
> ```shell
> git clone https://github.com/sooperset/mcp-atlassian.git
> cd ~/Documents/mcp_atlassian
> ```
> 
>     2. Set up your `.env` file with your Atlassian credentials
> 
>     3. Run the package using:
> 
> 
> ```shell
> uv --directory ~/Documents/mcp_atlassian run mcp-atlassian
> ```
ok, this is the output I get by doing running it manually like you asked:

![image](https://github.com/user-attachments/assets/6b75b93a-a5fc-4b7f-a77a-e6fb0c41937f)

IDK if it's supposed to stay like this though, it's been like that for a while. 

Meanwhile, in Cline I get the following:

![image](https://github.com/user-attachments/assets/8b44c518-ef55-4e3e-9869-48418d860046)

Is it strictly necessary to ask for this vesion of Python? I am in an up-to-date Manjaro, which usually get all but the bleeding edge of everything. Maybe 3.12 could do the trick?

**Comment by M-Gonzalo** [comment]
By doing the following I could get the server to work:

*cline_mcp_settings.json*
```json
      "command": "uv",
      "args": [
        "--directory",
        "/home/gonzalo/Documents/mcp-atlassian",
        "run",
        "mcp-atlassian"
      ],
```

So I guess it's a problem of how `uvx` manages the installation of the tool

**Comment by sooperset** [comment]
I'm using Claude desktop, it works well with the `uvx` setting. but I'll add `uv` config to README as well. thanks for pointing out!
